name: Build and push container
on:
  push:
    tags:
      - '*'
env:
  DOCKERFILE:  Dockerfile
  TAG:  kms-generic
  DOCKERHUB_IMAGE_ID: "qcdis/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker
        run: |
          cd  search_engine_app && docker build . --file $DOCKERFILE -t $TAG

      - name: Start docker
        run: |
          docker run -d -p 8000:8000 -host=172.17.0.2 $TAG:latest


      - name: Login to github Registry
        uses: docker/login-action@v1
        with:
          registry: "https://index.docker.io/v1/"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image to container Registry
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID=$DOCKERHUB_IMAGE_ID$TAG
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $TAG $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          docker tag $TAG $IMAGE_ID:latest
          docker push $IMAGE_ID:latest